### ISSUE TITLE
"APG" used in header before being defined

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-aria-practices#100]
W3C/WAI site guidelines state Acronyms/Initialisms/abbreviations should be defined on first use.

https://www.w3.org/WAI/ARIA/apg/

"APG Resources"

I see why, but maybe can add to the info box above, in it's  title, eg:

"ARIA Authoring Practices (APG) Guide Home"

It's also use in the first navigation item - but there's no other realistic alternative there.

**Comment by SteveALee** [comment]
CC @shawna-slh

**Comment by shawna-slh** [comment]
Isn't the first text on the pages "ARIA Authoring Practices Guide (APG)" ?

**Comment by shawna-slh** [comment]
I added this for ARIA: https://github.com/w3c/wai-aria-practices/issues/104

**Comment by mcking65** [comment]
Yes, the term APG is defined in the banner. I think that satisfies this requirement.

**Comment by mcking65** [comment]
in w3c/aria-practices#2379, I also propose that (APG) be added to the h1 on the home page.
