### ISSUE TITLE
Site CSS causing low contrast on hover in examples

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-aria-practices#105]
from https://twitter.com/dan_jolley/status/1527628280249126913
Hi there, great work and really useful, but I just spotted an issue with colour contrast on mouse hover on the accordion example. [[https://w3.org/WAI/ARIA/apg/e](https://t.co/Wfk1jvgX8C)](https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.html)

![image](https://user-images.githubusercontent.com/6991814/169624115-ae9fe7fe-393d-4fc8-bb82-f5b02b421467.png)

**Comment by mcking65** [comment]
@a11ydoer or anyone else who can see the image ...

Is this bug specific to the accordion example code or is it an issue with multiple pages in the site? If the former, I will transfer this to the aria-practices repo.

**Comment by richnoah** [comment]
@mcking65 here is a text description of what is occurring in the image posted. On the [Accordion Example page](https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.html) The default state of the accordion the text is a dark color against a very light grey background.  On hover, the text changes to white against a light blue background and is barely readable to a sighted person.

I only found this condition occurring on the Accordion Example page and not in any of the other examples.

**Comment by richnoah** [comment]
This is also found on the sortable table example: https://www.w3.org/WAI/ARIA/apg/example-index/table/sortable-table.html

**Comment by jnurthen** [comment]
CSS this is coming from is noted in https://github.com/w3c/aria-practices/issues/2333
