### ISSUE TITLE
Update Read This First Banner

### ISSUE THREAD

**Issue by richnoah** [w3c/wai-aria-practices#115]
On the ARIA Authoring Practices Guide (APG) https://www.w3.org/WAI/ARIA/apg/ there is currently a Read This First banner section on both the [Patterns](https://www.w3.org/WAI/ARIA/apg/patterns/) and [Practices](https://www.w3.org/WAI/ARIA/apg/practices/) pages.

The current structure of the banner is a graphic to the left, followed by a heading, Read This First, with a link to the [Read Me First page](https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/) and then followed by text. 

This request is to restructure the contents of the banner.

The image will remain the same.  Remove the link from the H2 of Read This First.  The text would be changed and contain the link:

No ARIA is better than Bad ARIA. Before using any ARIA, [read this to understand why](https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/)

**Comment by mcking65** [comment]
Related to #116 

We'd like to have a consistent design for alerting readers to important pre-read and warnings. By making this change to the read this first component, we can re-use the visual design for the example warnings that will be addressed by #116.
