### ISSUE TITLE
High contrast mode - link outline makes copy very hard to read

### ISSUE THREAD

**Issue by jnurthen** [w3c/wai-aria-practices#144]
When running in high contrast mode the transparent outline of links makes the copy very hard to read. I'd suggest removing the transparent outline for links.

<img width="850" alt="Screen shot showing links in yellow with a yellow outline around them which butts up against all the surrounding text making it very hard to read" src="https://user-images.githubusercontent.com/1724479/176255058-b31ceffb-2e0d-4d2f-a066-ff71b9d1baab.png">

**Comment by jnurthen** [comment]
(filed issue against WAI Website as I think this comes from there)

**Comment by shawna-slh** [comment]
fixed. apologies that it took a while.
