### ISSUE TITLE
Generating Preview Links

### ISSUE THREAD

**Issue by alflennik** [w3c/wai-aria-practices#171]
Currently there are caching problems with Netlify making it difficult to get the existing Netlify setup to produce a preview link. @mcking65 needs a preview link to send to a group of volunteers who will check various pages of the site for issues.

As a short term solution, I used Bocoup's Netlify account to generate a preview link here: https://eloquent-palmier-c2b66e.netlify.app/aria/apg/ . Although the domain name is different, everything else is representative of what the broken Netlify will produce once the caching issue is fixed.

A long term solution is needed to fix build links going forward.

**Comment by alflennik** [comment]
We have updated the URL for the new Netlify account, [aria-practices.netlify.app/aria/apg/](https://aria-practices.netlify.app/aria/apg/), and I've set up our automated tooling to use the new account. A follow-up step will be to delete the old Netlify account to prevent confusion.

**Comment by alflennik** [comment]
Hi @SteveALee, in the flurry of activity to get aria-practices PR 2417 merged, the quickest solution to fix Netlify was to create a new account, aria-practices.netlify.app. Now that I have the new account working, would you mind deleting the wai-aria-pratices2.netflify.app to prevent confusion and to prevent all the PRs from erroneously being marked as broken?

**Comment by SteveALee** [comment]
Will do

**Comment by SteveALee** [comment]
Actually, we need a linked Netlify site (not account) that is owned by the w3c team account, like all the others.

In addition there is a naming convention. I add the 2 suffix as the names are in a global namespace and someone has the desired name.

You could transfer the site to us after renaming. But what required fixing?

Thanks

**Comment by mcking65** [comment]
@howard-e 

Is this issue fully resolved?

**Comment by daniel-montalvo** [comment]
As @mcking65 commented, I'm also interested in knowing if this is fully resolved or there's something else needed, @alflennik

**Comment by alflennik** [comment]
Hi @daniel-montalvo, no, I don't believe it's fully resolved, I still see references to wai-aria-practices2 present in the PRs. For this to be resolved my expectation is that the old Netlify account for wai-aria-practices2 would no longer appear anywhere.

**Comment by daniel-montalvo** [comment]
Thanks @alflennik 
Will have a look.

**Comment by alflennik** [comment]
Big thanks @daniel-montalvo! If it's possible to fully delete wai-aria-practices2.netlify.com, that to me would be the ideal outcome.

**Comment by daniel-montalvo** [comment]
@alflennik I deleted this Netlify account before the holiday, I just forgot to update this issue :-)

Let's keep this open until we go about our next publication and see if things have improved after deletion. If so, I'd say we could close this.

**Comment by alflennik** [comment]
Fantastic! Thank you @daniel-montalvo! I opened a test PR and verified that only one Netlify account is linked. I will close!
