### ISSUE TITLE
Broken image links on feed display page

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#190]
there is another issue which PR #187 doesn't address and we still have to fix: there are now broken image links in the feedDisplay page.

That example dynamically creates images, which, as of the release yesterday, is not something we support, because on the final deploy the images will be stored in a different directory than the source code. All of the content and assets for the entire site will be split up into three groups, a content folder for html files, a content-images folder for images, and a content-assets folder for everything else.

Personally, while the site does currently work, I think the mental overhead of making sure the APG supports its html, images and assets being automatically divided up into three directories when deployed is not a good long-term solution.

_Originally posted by @alflennik in https://github.com/w3c/wai-aria-practices/issues/186#issuecomment-1412186930_

**Comment by mcking65** [comment]
@alflennik 

With PR w3c/aria-practices#2417 we didn't make any changes that would have changed how images were referenced from the feed display page. So, how did this regression occur?

**Comment by alflennik** [comment]
Hi @mcking65, the changes were in wai-aria-practices https://github.com/w3c/wai-aria-practices/pull/187 and we edited the build scripts to split up the three types of content. Fortunately there were limited repercussions beyond the feed display example.

**Comment by mcking65** [comment]
Fixed by w3c/aria-practices#2729
