### ISSUE TITLE
2 Grid and 2 Landmark pages lead to 404 when accessed via redirects due to casing of file names

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#192]
We have 4 legacy URLs that still lead to 404 errors.

#### Data Grids Example Page
* Legacy URL we are redirecting: https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html
* Current redirect Points to: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/datagrids/
* Functional location: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/dataGrids/

because people could be bookmarking the current functional location, it seems like we should change the redirect to point to the functional location. Then, we land [Pull Request #2597](https://github.com/w3c/aria-practices/pull/2597) and add another redirect to the renamed file.

#### Layout Grids example page
* Legacy URL we are redirecting: https://www.w3.org/WAI/ARIA/apg/example-index/grid/LayoutGrids.html
* Current redirect: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layoutgrids/
* Functional location: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/LayoutGrids/

because people could be bookmarking the current functional location, it seems like we should change the redirect to point to the functional location. Then, we land [Pull Request #2597](https://github.com/w3c/aria-practices/pull/2597) and add another redirect to the renamed file.

#### Landmark Examples: HTML Sectioning Elements page
* Legacy URL we are redirecting: https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/HTML5.html
* Current redirect Points to: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/html5
* Functional location 1: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/HTML5
* Functional location 2: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/HTML5.html

Should we leave the redirect as is and rename `content/patterns/landmarks/examples/HTML5.html` to `content/patterns/landmarks/examples/html5.html`? Perhaps add this change to w3c/aria-practices#2597?

#### Landmark Examples: General Principles page
* Legacy URL we are redirecting: https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/index.html
* Current redirect Points to: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/index
* Functional location 1: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles
* Functional location 2: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html

Is the best solution to change the redirect to point to functional location 1?

@alflennik wrote:
>I looked into the datagrids and layout grids a little bit more and found that the WAI website seems to automatically remove capitalized letters from URLs. This is why the links on the site work but bookmarked pages don't.
>
>I think the pages already have a bit of a strange naming convention, given that no other pages have capitalized letters, so a good solution would probably be to rename those two files in the aria-practices repo and introduce new redirects from the old urls to the new ones.

_Originally posted by @alflennik in https://github.com/w3c/wai-aria-practices/issues/186#issuecomment-1412195791_

**Comment by a11ydoer** [comment]
@alflennik can you share the order of actions you mentioned at the APG meeting on 2/14/2023?

**Comment by alflennik** [comment]
@mcking65 @a11ydoer we can safely merge https://github.com/w3c/aria-practices/pull/2597 and following that I will create a new publication branch, inform the WAI team, and document the changes we need to make to the redirects.

**Comment by alflennik** [comment]
@mcking65 shall we close this issue following the deploy last week?

**Comment by mcking65** [comment]
Yes. Closed by w3c/aria-practices#2597 and #200.
