### ISSUE TITLE
[AT support sections] use existing design pattern for expandable warning box [was: affordance of expand]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-aria-practices#212]
I missed that the "Warning! Unapproved Report" was expandable to reveal more information.

Is there a reason not use the same UI design, interaction, code, etc. as the "Read This First" expandable warning box at the top of the pages? [example](https://www.w3.org/WAI/ARIA/apg/patterns/button/examples/button/#support-notice-header)

**Comment by mcking65** [comment]
Visually, what is the disclosure missing that it should have? I can't tell the difference as a screen reader users. Both are appropriately marked up.

**Comment by iadawn** [comment]
The current icon on the disclosure widget is exclamation mark (bang) in a grey circle. This hints at this just being a warning. It may be more helpful to use a triangle or greater than sign as this hints at the disclusure action. The icon could then change rotation to point downwards when the widget is revealled.

<img width="324" alt="screenshot of unapproved report widget with right pointing filled arrow" src="https://user-images.githubusercontent.com/2444840/231415133-6a4c2742-c34f-4741-9a97-d1fc1ee8d755.png">

**Comment by shawna-slh** [comment]
I updated the issue title and my initial comment to more clearly ask if there is a reason not to use the current design pattern.

**Comment by mcking65** [comment]
@isaacdurazo Please comment on this

**Comment by isaacdurazo** [comment]
When we designed the mockups for the embedded reports, the intention was to have a section above the table that displayed information about the report being generated from candidate tests. It was not a disclosure nor a warning message. 

The original design was:

1. A heading that reads "Candidate Report" with the same visual label style we use in ARIA AT. This now reads "Warning! Unapproved Report", but still has the label style.
2. A paragraph that reads: 
   - The information in this report is generated from candidate tests. Candidate aria-at tests are in review by assistive technology developers and lack consensus regarding:
      - applicability and validity of the tests, and
      - accuracy of test results.

I'm not sure at what point this design changed during implementation, but I think we should either make it look like the existing "Read This First" disclosure or make it so the content is always visible.

I'm also noticing the font size is smaller than the rest, so it might be a good opportunity to fix that as well.

**Comment by ccanash** [comment]
Thank you Isaac . @mcking65 Let me know if we should prioratize this. We could tackle it while we unblock some items from the refactor project.

**Comment by ccanash** [comment]
HI @mcking65 , a preview of this PR has been deployed here: https://aria-at-app-sandbox.bocoup.com/embed/reports/modal-dialog
