### ISSUE TITLE
[AT support tables] no data

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-aria-practices#213]
"No Data" seems like there could be something there, but it's missing. Perhaps "not applicable" would be more appropriate?

![image](https://user-images.githubusercontent.com/6991814/231310970-de29ec7a-515a-4871-9b91-80dafcb3c696.png)

**Comment by mcking65** [comment]
Correct, there are two options: data is not yet available (e.g. VO/Chrome) and the cell is not applicable (e.g., JAWS/Safari).

In [this comment on aria-practices PR 2569](https://github.com/w3c/aria-practices/pull/2569#issuecomment-1398008506), see the heading "Options for cells that do not contain data".

Unfortunately, for now we had to go with option B.

This is part of the iframe content delivered by the aria-at-app. I couldn't find an issue tracking the need for option A, so just created w3c/aria-at-app#598.

**Comment by mcking65** [comment]
Fixed by w3c/aria-at-app#583
