### ISSUE TITLE
Remove `feedDisplay` images transform

### ISSUE THREAD

**Issue by howard-e** [w3c/wai-aria-practices#225]
#190 describes the rating images for the feed's display example failing to load. #224 implements a stopgap fix to address this concern.

This should only be temporary until further research is looked into for how the we can package the image assets together with the feed display's content, when creating the Jekyll build that's deployed on the WAI website.

**Comment by mcking65** [comment]
@howard-e 

Now that w3c/aria-practices#2729 is merged, this issue can be resolved.

**Comment by howard-e** [comment]
> @howard-e
> 
> Now that [w3c/aria-practices#2729](https://github.com/w3c/aria-practices/pull/2729) is merged, this issue can be resolved.

@mcking65 #245
