### ISSUE TITLE
404 for landmarks pattern on WAI website but not on deploy previews

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-aria-practices#233]
The link on [This preview for PR 227](https://deploy-preview-227--wai-aria-practices2.netlify.app/aria/apg/patterns/landmarks/) workss but the link on the [WAI website](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/) does not.

**Comment by mcking65** [comment]
It is working now. Thank you to whoever resolved the issue.
