### ISSUE TITLE
Hide extraneous "Skip to main" link

### ISSUE THREAD

**Issue by s3ththompson** [w3c/wai-aria-practices#26]
We currently have 2 "Skip to main" links. One is from APG, the other is injected from the Supplemental Resource parent template.

We should hide the one from the parent template so that only one "Skip to main" link is present.

(In a future issue, we will mitigate the root issue by working to improve the parent "Skip to main" link from the parent template.)

**Comment by shawna-slh** [comment]
> We should hide the one from the parent template so that only one "Skip to main" link is present.

For consistency, would be better to use the parent one.

> (In a future issue, we will mitigate the root issue by working to improve the parent "Skip to main" link from the parent template.)

Happy to have improvements to parent! If that needs to wait for future, OK.

**Comment by mcking65** [comment]
@shawna-slh wrote: 

> > We should hide the one from the parent template so that only one "Skip to main" link is present.
> 
> For consistency, would be better to use the parent one.

Shawn, the parent one is less functional than the one we have already made available on all example pages in TR today. So, if we use the parent one, the APG examples in the WAI site would end up being both inconsistent with the current APG and less functional than the current APG. The task force has discussed this and would like to move forward with the APG skipto functionality to ensure consistency with the current APG.

> > (In a future issue, we will mitigate the root issue by working to improve the parent "Skip to main" link from the parent template.)
> 
> Happy to have improvements to parent! If that needs to wait for future, OK.

For the time being, this can be a high priority backlog issue.

@richnoah do we already have an issue to track upgrading the template skipto functionality?

Note that this is separate from making skipto persistently visible; that is a longer term design issue.

**Comment by richnoah** [comment]
@mcking65 I am currently tracking work against the Mockup Issue.  Issue #40

**Comment by mcking65** [comment]
@richnoah 

#40 is about making skipto persistently visible.

There should be a separate issue raised against the WAI template that upgrades it from a "skip to main" link with only one target to a more functional skip menu that can be accessed with alt+0 from any location on the page.

@shawna-slh do we raise such issues in
https://github.com/w3c/wai-minimal-header-design

**Comment by mcking65** [comment]
Yesterday, this was resolved in #62. However, now, instead of the APG skipto menu, we have only the static skip to content link. So, there is only one, but unfortunately it is the wrong one.

**Comment by mcking65** [comment]
Verified still fixed after today's changes to #62.
