### ISSUE TITLE
Name top-level navigation region "APG"

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#47]
Currently the top-level navigation region that includes links for Home, Patterns and Widgets, etc., is named "Context for this document". That is not a suitable name.

The most effective name for a navigation region is a simple, clear, and brief string that tells the user what using the elements inside the navigation region will navigate. So, for example, the top-level navigation in the APG is navigating across all of APG. So, an ideal name is "APG". I think the acronym is better here because brevity in the landmark region that you use most often is especially valueable. This will only work if we have APG expanded elsewhere, like in the banner.

**Comment by shawna-slh** [comment]
I will look at this with Steve.

(Matt suggests it should be context-specific parameter. Default could "site", though that's not ideal.)

**Comment by SteveALee** [comment]
We've updated the layout and it would appear the old one is being used here. I'll look into it once I get a local build working correctly.

**Comment by SteveALee** [comment]
I cannot find "Context for this document" at all it was changed to`Item navigation` so perhaps you were looking and an old preview that does not use the `standalone_resource` layout? We are about to make a couple of further changes here.

If you find an example please provide a link to it. Thanks

**Comment by mcking65** [comment]
@SteveALee wrote:

> I cannot find "Context for this document" at all it was changed to`Item navigation` so perhaps you were looking and an old preview that does not use the `standalone_resource` layout? We are about to make a couple of further changes here.
> 
> If you find an example please provide a link to it. Thanks

Looking across the site, I can no longer find the old label. I find only "item navigation" now.

Unfortunately, "Item navigation" is not a helpful name. The term "item" does not have any meaning as you navigate the rules site or the supplemental guidance site. There is nothing in the design clearly demarked as an "item".

In addition, the word "navigation" should not be included in the name of a nav element because this causes it to be announced as "item navigation navigation region".

On the rules site, I recommend naming that nav element "Rule". Screen reader users would then hear "Rule Navigation Region". Similarly, on the guidance site, I'd recommend naming it "Guidance".

On the APG site, we will name the top-level navigation "APG" because those are the links that navigate across all of APG.

I hope you can change the nav component to expect a name parameter. If a name parameter is not provided, you could provide a default value. In this case, as I mentioned to Shawn, I think "Site" might be an acceptable default.

An important follow up action would be to codemod all the pages to use a better name instead of the default, and once done, change the name prop to required to ensure the navigation is understandable across all of WAI.

**Comment by SteveALee** [comment]
Cc @shawna-slh 

Thanks for the very useful feedback. I agree the generic "item" is not particularly useful.

Actually, we now have config parameters that can make this work as follows in the three WAI site areas that currently use this navigation by setting 'type_of_guidance" to

- ACT Rule
- APG
- Cognitive Objective / Cognitive Pattern

(The last might benefit from being shorter)

This will appear in the nav for AT as per this issue, in the page HTML titile and optionally before the H1 heading for the item pages.

We can then follow this in other areas of the WAI site like the forthcoming Understanding. We can also add more uses of the parameter to the pages if required.

I feel this is a reasonable solution and uses two config parameters. While "type_of _guidance" may not be the most accurate parameter name, it is workable.

**Comment by mcking65** [comment]
Thank you @SteveALee! That sounds like a good solution! I like that it creates consistency between the nav name and site title.

>Cognitive Objective / Cognitive Pattern

Perhaps instead use:

>Cognitive Guidance

**Comment by richnoah** [comment]
@SteveALee we are using the latest template and I see the aria-label="Context for this document" in the <nav>:

`

<body id="top" class="page-aria-authoring-practices-guide ">
--
  | <a href="#main" class="button button--skip-link">Skip to content</a>
  |  
  | <div class="minimal-header-container default-grid">
  |  
  | <div class="minimal-header" id="site-header">
  | <div class="minimal-header-container">
  | <div class="minimal-header-name">
  | ARIA Authoring Practices
  | </div>
  |  
  | </div>
  |  
  | <div class="minimal-header-logo">
  | <a href="http://w3.org/">
  | <img alt="W3C" src="/assets/images/w3c2.svg" width="92" height="44"/>
  | </a>
  | <a href="/">
  | <img alt="Web Accessibility Initiative" src="/assets/images/wai.svg"/>
  | </a>
  | </div>
  | </div>
  |  
  | </div>
  |  
  | <div class="default-grid nav-container">
  | <div class="nav" >
  |  
  | <nav class="nav" aria-label="Context for this document">
  | <ul>
  |  
  | <li class="nav__item"><a href="/" class="active" aria-current="page">Home</a></li>
  |  
  | <li class="nav__item"><a href="/patterns/">Patterns and Widgets</a></li>
  |  
  | <li class="nav__item"><a href="/index/index.html">Index</a></li>
  |  
  | <li class="nav__item"><a href="/fundamentals/">Fundamentals</a></li>
  |  
  | <li class="nav__item"><a href="/about/">About</a></li>
  |  
  | <li class="nav__item"><a href="https://www.w3.org/WAI/standards-guidelines/wcag/docs/">
  | All WCAG 2 Guidance
  | <svg focusable="false" aria-hidden="true" class="icon-different-view "><use xlink:href="/assets/images/icons.svg#icon-different-view"></use></svg>
  | </a></li>
  | </ul>
  | </nav>
  |  
  | </div>
  | </div>
  | <div class="default-grid with-gap leftcol">

<body id="top" class="page-aria-authoring-practices-guide ">
    <a href="[#main](https://main--wai-aria-practices2.netlify.app/#main)" class="button button--skip-link">Skip to content</a>

   <div class="minimal-header-container default-grid">
      
      <div class="minimal-header" id="site-header">
  <div class="minimal-header-container">
    <div class="minimal-header-name">
        ARIA Authoring Practices
    </div>
    
  </div>
  
  <div class="minimal-header-logo">
        <a href="http://w3.org/">
            <img alt="W3C" src="[/assets/images/w3c2.svg](https://main--wai-aria-practices2.netlify.app/assets/images/w3c2.svg)" width="92" height="44"/>
        </a>
        <a href="[/](https://main--wai-aria-practices2.netlify.app/)">
            <img alt="Web Accessibility Initiative" src="[/assets/images/wai.svg](https://main--wai-aria-practices2.netlify.app/assets/images/wai.svg)"/>
        </a>
    </div>
</div>

    </div>

    <div class="default-grid nav-container">
        <div class="nav" >
          
           <nav class="nav" aria-label="Context for this document">
            <ul>
            
                <li class="nav__item"><a href="[/](https://main--wai-aria-practices2.netlify.app/)" class="active" aria-current="page">Home</a></li>
            
                <li class="nav__item"><a href="[/patterns/](https://main--wai-aria-practices2.netlify.app/patterns/)">Patterns and Widgets</a></li>
            
                <li class="nav__item"><a href="[/index/index.html](https://main--wai-aria-practices2.netlify.app/index/index.html)">Index</a></li>
            
                <li class="nav__item"><a href="[/fundamentals/](https://main--wai-aria-practices2.netlify.app/fundamentals/)">Fundamentals</a></li>
            
                <li class="nav__item"><a href="[/about/](https://main--wai-aria-practices2.netlify.app/about/)">About</a></li>
            
            <li class="nav__item"><a href="https://www.w3.org/WAI/standards-guidelines/wcag/docs/">
                All WCAG 2 Guidance
                <svg focusable="false" aria-hidden="true" class="icon-different-view "><use xlink:href="/assets/images/icons.svg#icon-different-view"></use></svg>
            </a></li>
            </ul>
          </nav>
          
        </div>
    </div>
    <div class="default-grid with-gap leftcol">`

**Comment by SteveALee** [comment]
@richnoah can you please supply the URI that occurs in.

**Comment by richnoah** [comment]
@SteveALee it is occurring in the <nav> section for every page on the prototype https://main--wai-aria-practices2.netlify.app/

**Comment by SteveALee** [comment]
Got it! Should be fixed next time you build.

**Comment by mcking65** [comment]
I have reviewed the preview for #62, and this issue is addressed.

**Comment by mcking65** [comment]
Verified still fixed after today's changes to #62.
