### ISSUE TITLE
Move "Read me first" content from "About" page to its own page within fundamentals section

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#48]
The content from the section [Read me first](https://w3c.github.io/aria-practices/#read_me_first) needs to have its own fundamentals page that is a sibling of the sections for landmarks and accessible names. It is currently buried in the "About" page; it should be removed from there.

Per suggestion from @shawna-slh, change the title to "Read This First".

List it first on the fundamentals page.

Also List it first on the patterns and widgets page.

We will also need to find a good spot for it on the home page, perhaps as the first resource.

**Comment by richnoah** [comment]
@mcking65 for the request of listing the Read This First content on the Patterns and Widgets page are you wanting this in a card or in a new design element?  The cards on the page are currently ordered alphabetically and inserting this content would break that organizational structure.

**Comment by mcking65** [comment]
@richnoah 

For launch, it is essential that it is first on fundamentals page.

For launch, there will also have to be at least one of either a patterns or home page placement requirement, but I want to discuss it first at today's meeting.

**Comment by mcking65** [comment]
@richnoah, @isaacdurazo, note that I made minor clarifications to the to-do list in Rich's comment.

**Comment by mcking65** [comment]
Yesterday this was addressed. Today, in the preview of #62, the link on the practices page to read this first page is broken.

**Comment by mcking65** [comment]
The links are all fixed in the preview of #62, and this issue is addressed.

**Comment by mcking65** [comment]
Verified still fixed after today's changes to #62.
