### ISSUE TITLE
Complementary region for help improve this page is missing accessible name

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#52]
Could be fixed by w3c/wai-minimal-header-design#97

Otherwise, specify aria-label="feedback" on the complementary region containing the "Help Improve This Page" content.

**Comment by richnoah** [comment]
@mcking65 it has been determined that this is also governed by the template.  Please advise if you would like this assigned to Shawn.

**Comment by mcking65** [comment]
@shawna-slh 

Is it possible that w3c/wai-minimal-header-design#97 could get fixed before May 11? Will the Bocoup team have to do anything to inherit the new label once fixed?

**Comment by mcking65** [comment]
I have reviewed the preview of #62, and this issue is addressed.

**Comment by mcking65** [comment]
Verified still fixed after today's changes to #62.
