### ISSUE TITLE
Design element for highlighting and linking to Read This First Section

### ISSUE THREAD

**Issue by richnoah** [w3c/wai-aria-practices#58]
After the H1 and above the cards on the Fundamentals and Design Patterns and Widgets pages, display an element that will draw the user's attention to the following link and text:

>[Read This First](#)
>No ARIA is better than Bad ARIA. Before using any ARIA, it is essential to understand why.

Include a visual element, icon or symbol, that accompanies this link and text to help call attention to it.

**Comment by mcking65** [comment]
@richnoah, @isaacdurazo 

I revised the initial comment in this thread for clarity. I specified that we need a linkand shortened the text substantially. I hope this simplifies the design by requiring much less space and making it easier to read.

**Comment by isaacdurazo** [comment]
a PR for this has just been submitted: https://github.com/w3c/wai-aria-practices/pull/63

**Comment by mcking65** [comment]
Verified beautifully fixed in #62!
