### ISSUE TITLE
Update "Help Improve this Section" to point to APG email

### ISSUE THREAD

**Issue by s3ththompson** [w3c/wai-aria-practices#59]
"Help Improve this Section" should use the public-aria-practices@w3.org rather than wai-eo-editors@w3.org.

For now we will postpone the larger improvements in issue #25.

Edit: fixed email above per @shawna-slh’s correction below

**Comment by shawna-slh** [comment]
I think you want this e-mail address:

```public-aria-practices@w3.org```

@a11ydoer @mcking65 Is that the correct e-mail address for public comments?

For main WAI website, we put this in the frontmatter:

```feedbackmail: public-aria-practices@w3.org```

@SteveALee - is that correct for this template, too?

**Comment by s3ththompson** [comment]
Oops, I copied the wrong the email! That’s the one I meant… going to update the original

**Comment by a11ydoer** [comment]
@shawna-slh that is the correct email address.

**Comment by mcking65** [comment]
I have reviewed the preview of #62, and this issue is addressed.

**Comment by mcking65** [comment]
Verified still fixed after today's changes to #62.
