### ISSUE TITLE
Home page builder retains deleted content and semantics

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#65]
This is important for launch.

When the [w3c/aria-practices/index.html file](https://github.com/w3c/aria-practices/blob/main/index.html)
 is processed to build the [content/index.md file](https://github.com/w3c/wai-aria-practices/blob/main/content/index.md) , it is including deleted content and re-arranging content. I may be trying to have it do something it was not designed to do, however the fallback in this scenario is itself concerning me, especially keeping content that was deleted. I'll describe the two issues I have noticed related to keeping deleted content and deleted semantics. Then, I'll describe the end goal I am hoping to achieve.

### Incorrectly retained deleted content

In [APG pull 2309](https://github.com/w3c/aria-practices/commit/437204e4fb165eec4888a8698374547d6a6269a4),
I removed lines 37-40 from the index.html file. Yet, after the PR was merged and the APG site was built and other changes in that PR are rendered, the content from those lines is still on lines 49-53 in
[content/index.md](https://github.com/w3c/wai-aria-practices/blob/main/content/index.md?plain=1):

~~~
49        <p>
50            Learn how to make common rich internet application patterns and
51            widgets accessible by applying WAI-ARIA roles, states and
52            properties, and implementing keyboard support.
53          </p>
~~~

#### Retained deleted semantics

In [APG PR 2312](https://github.com/w3c/aria-practices/pull/2312/files),
I changed the H3 on line 35 to a paragraph. However, the H3 remains on line 48 of
[content/index.md](https://github.com/w3c/wai-aria-practices/blob/apg/home-resources/content/index.md?plain=1).
Since I didn't specify content for that H3, the code duplicated the content from the subsequent H3.

~~~
47        <h2>APG Resources</h2>
48        <h3>Design Patterns and Widgets</h3>
49        <p>Building blocks that help you make the web accessible</p>
~~~

#### What I'd like to get

The design has an H2 that titles each section of cards, e.g., `<h2>APG Resources</h2>`.
That H2 is followed by 2 elements of content before the first card, an H3, and a paragraph.
Because each card is an H3, this creates a confusing experience for a screen reader user.
The content in the paragraph is not really adding value, so I'd like to have only one content element after the section title. That element would be a short paragraph. For example, the desired rendering for the APG resources section is:

~~~
<h2>APG Resources</h2>
<p>Building blocks that help you make the web accessible</p>
~~~

That would then be followed by the H3 for the first card.

I'd like to have this reduced format for all sections after APG resources as well.

**Comment by richnoah** [comment]
@mcking65 the issue stems from the fact that the build was looking for an H3.  We will be removing the H3 and will be using the H2 followed by the p tag.  After the PR lands, there will have to be visual styling updates as the current H2 and p tags are very similar and do not offer enough visual distinction for sighted users.

**Comment by isaacdurazo** [comment]
Styling for H2 has been address [in this commit](https://github.com/w3c/wai-aria-practices/pull/62/commits/6b9c33f481bdad46bd3de60b7c348b6ae751d5fa)

**Comment by mcking65** [comment]
Just from inspecting current state of files, I think this is fixed. The final test will happen after #62 is merged to main, and after I merge the PR to update the content in the first paragraph under the first H2 (APG Resources).
