### ISSUE TITLE
Change H1 container from `header` to `div` to avoid undesirable landmark

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#69]
H1 elements are contained in a header element, e.g.:

~~~
        <header>
            <h1>
              Combobox
            </h1>
        </header>
~~~

Gecko and Webkit are mapping the header to a ARIA banner, creating a useless landmark region that creates excess screen reader verbosity. I think this may be a browser bug, but not one that is likely to be resolved soon. The work around is trivial. The best solution is to change the `header` element to a ``div` element. Alternatively, we can add `role="none"` to the header element.

**Comment by richnoah** [comment]
Issue filed in wai-minimal-header-design; [https://github.com/w3c/wai-minimal-header-design/issues/103](https://github.com/w3c/wai-minimal-header-design/issues/103)
