### ISSUE TITLE
Top-navigation: Move index between practices and about

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#77]
@isaacdurazo, the "Index" link feels out of place to me. It seems like we should have the two primary sections, patterns and practices, juxtaposed. What do you think of moving Index between practices and about?

Consider how I have described the APG structure in the new [Introduction section](https://wai-aria-practices2.netlify.app/about/):

>The APG is organized into two major sections: patterns and practices. Each pattern explains how to make a common user interface element, such as a button, menu, or dialog, accessible, and provides functional example implementations of the pattern. The practices section gives in-depth explanation of how to satisfy a variety of accessibility needs that surface when making rich internet application experiences accessible. For instance, the practices section on providing accessible names and descriptions gives detailed descriptions of seven different naming techniques as well as a table providing guidance for naming more than 80 types of elements.

Also consider that the index page will eventually cover all content, not just examples.

_Originally posted by @mcking65 in https://github.com/w3c/wai-aria-practices/issues/60#issuecomment-1123073890_

**Comment by isaacdurazo** [comment]
This issue has been addressed [in this commit](https://github.com/w3c/wai-aria-practices/pull/62/commits/5d5163f897355fca00ccc8081298a310379c6f03). Sorry I reference the original [issue](60) where this was mentioned

**Comment by mcking65** [comment]
Verified fixed in #62!
