### ISSUE TITLE
Set github.path for all pages [Required for Launch]

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-aria-practices#79]
eg for `about.md`

```yaml
github:
  repository: w3c/aria-practices
  path: content/about.md
```

**Comment by mcking65** [comment]
@richnoah this is in the done column in the project; is it ready to close? I'm not sure how to verify this for all pages. I'm assuming someone did that before moving to done?

**Comment by richnoah** [comment]
@mcking65 this was done the deploy of 5/13 and is part of the build process.
