### ISSUE TITLE
Change path of example URIs so examples are in subdirectory of their respective pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#80]
Change the URI path of examples so an example implementation of a pattern is in a subdirectory of the pattern.

For instance, for combobox examples, instead of the examples being in `/index/` like this:

~~~
/examples-index/combobox/combobox-autocomplete-both.html
/examples-index/combobox/combobox-autocomplete-list.html
/examples-index/combobox/combobox-autocomplete-none.html
~~~

Make the URI path to be /patterns/PATTERN_DIR/examples, like this:

~~~
/patterns/combobox/examples/combobox/combobox-autocomplete-both.html
/patterns/combobox/examples/combobox/combobox-autocomplete-list.html
/patterns/combobox/examples/combobox/combobox-autocomplete-none.html
~~~

This will re-enforce the relationship between a pattern and its examples.

It would be good to do this as soon as possible to avoid bookmark churn for users.

_Originally posted by @mcking65 in https://github.com/w3c/wai-aria-practices/issues/76#issuecomment-1123988967_

**Comment by alflennik** [comment]
We discussed this and I want to just share my understanding about the best way to tackle this. If it doesn't jive with your expectation @mcking65 let me know.

1. We update the APG repo to organize the files in the way Matt described above, in a branch. This may necessitate a temporary content freeze, or at least any fixes would need to be applied in both main and the updated branch.
2. Once the content is organized, we can then update the wai-aria-practices repo to support the new content organization, resulting in new URLs like the ones described above.

Let me know if anything is missing here. For example I understand we want to set up redirects from the existing URL structure to the new URL structure.

**Comment by mcking65** [comment]
@alflennik this is correct at a high level. The huge piece of work is the reorganization of content. I have mapped that out in w3c/aria-practices#2418 and begun work in w3c/aria-practices#2417. I'd like to discuss that work during the APG meeting this week if possible.

**Comment by mcking65** [comment]
work done by w3c/aria-practices#2417 is now complete and published; closing.
