### ISSUE TITLE
Home page: links to patterns and practices have incorrect href

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#83]
The links to the patterns and practices in the body of the home page are not using the new full paths in the href values, so they are failing.

Should we be fixing this in the home page file in the aria-practices repo? Perhaps this issue should be in that repo.

**Comment by richnoah** [comment]
@mcking65 I believe you opened this while work was going on to solve the permalinks issue.  I just checked all the links on the homepage and they are working in https://deploy-preview-62--wai-aria-practices2.netlify.app/aria/apg/
