### ISSUE TITLE
Need clarification of publication process

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-aria-practices#85]
# Build and publication

CC @shawna-slh FYI

The build of this resource appears to be two step

- prebuild shell script to generate the examples
- jekyll SSG build

What is the correct workflow for updates publication?

My expectations are:

- Jekyll source files are updated
- and /or examples are updated and regenerated
- preview using local dev or netlify PR preview 
- check with Shawn/Steve that is good time to publish
- commit and push to main
- Shawn publishes

Explicitly, the publish only grabs what is in main - does not run the  pre-build script

# Netlify build config

Currently the Netlify build calls `build.sh` but this now simply duplicates code already run. Can this be removed thus making the netlify build consistent with all other resources?

**Comment by alflennik** [comment]
@SteveALee Yes, I believe your assumptions are right. Thanks for making the fix in the launch-fixes branch.

**Comment by richnoah** [comment]
The publication process has been documented here: [https://wai-website-theme.netlify.app/workflow/](https://wai-website-theme.netlify.app/workflow/)
