### ISSUE TITLE
case redirect not working

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wai-aria-practices#91]
As I mentioned in #37, I expect the case-sensitive URI for the APG to be https://www.w3.org/WAI/ARIA/apg/ which puts it under the grandfathered uppercase /WAI/ARIA/ but uses the required lowercase for the new resource. There is a redirect that causes URIs like /wai/aria/ or /WAI/aria/ to redirect to /WAI/ARIA/. But that redirect is not working for this resource, it seems to have been deployed in a manner that bypasses the redirect, so the only case-sensitive URI that works is https://www.w3.org/WAI/aria/apg/. I think it either needs to be under the existing redirect system, or do its own redirecting to make sure that URIs with other cases still wind up at the canonical URI.

**Comment by shawna-slh** [comment]
Hopefully @SteveALee can shed some light on what happened with the capitalization. I'm afraid it's an issue with the site publication system. I'm not sure the challenges with changing that.

**Comment by SteveALee** [comment]
There is no specific redirection going on. Except for the Netlify previews which annoyingly changing everything to lowercase, at least in the address bar.

Looking at the published pages in the [gih-pages branch ](https://github.com/w3c/wai-website/tree/gh-pages/aria/apg) they all use `aria/apg`. I expect that would explain the issue and they should appear at `ARIA/apg`

I did mention mentioned that with my very limited understanding of the redirect I thought all permnlinks should be be `ARIA/apg` and I take your comments above to confirm that is the case.

So we need to edit all occurrences:

1. the permalink and ref in each page
2. the permalink and ref for the examples html files
3. the config.yml file in wai-website (and also the apg repo for consistency)
4. any more?

I'll do 3 ready for today's publication, but the rest need doing too by the APG team.

**Comment by SteveALee** [comment]
@shawn FYI I updated the wai-website _config.yml so any publication now will have updated links in the ARIA/apg page header and nav. Until the other changes are made this will result in 404s (now `ARIA` instead of `aria`)

**Comment by shawna-slh** [comment]
@alflennik @richnoah @michael-n-cooper 

Please confirm that indeed we want to and can correct the URI capitalization today?

**Comment by alflennik** [comment]
@shawna-slh We changed the capitalization of the code in the wai-aria-practices repo so it is now consistent with the expected state when deployed.

**Comment by richnoah** [comment]
@SteveALee I will be available at approximately 8am BST, 2am CDT, on IRC #aria-apg to answer any questions or provide any assistance.

The missing example-index folder is also impacting the delivery of a Jump To as described in [Issue 89](https://github.com/w3c/wai-aria-practices/issues/89)

**Comment by mcking65** [comment]
I am most confused that yesterday the URI resolution was not case sensitive. You could type w3.org/wai/aria/apg and the URI would resolve successfully and show the site. Since the most recent deploy, if you don't have WAI and ARIA in all caps, the URI yields a 404 for all pages across the site.

**Comment by SteveALee** [comment]
> We tried updating the symlink: https://github.com/w3c/wai-website/commit/667dc7cb5954f12e0446d8a3bfc5cb73397b38ad

That was the correct thing to do (sorry I forgot about mentioning that). However the link was corrupted with extra junk on the end of the target. I guess editing the "file" for symblinks in GitHub doesn't work, assuming that is whgat you did. I've always done it locally using the `ln -s` command.

Anyway is now fixed and release is running so hopefully still good for GAAD!?

**Comment by SteveALee** [comment]
@mcking65 I am also confused. You should always have used `/ARIA/apg` as URIs are case sensitive and that is what Shawn wanted. 

I do not understand what the new w3c case conversion redirection does that @michael-n-cooper mention at the top of this  issue.  

Hopefully it is now as required. But if `/aria/apg` is now supposed to work and does not I guess we have more work to do. Shawn and I need to better understand how it supposed to work so we can figure out what might be breaking it.

Does `WCAG\supplemental` work as expected - that should be have the same as far as I am concerned.

@michael-n-cooper can you please advise?

**Comment by richnoah** [comment]
Hello, @SteveALee thank you for the assistance.  Confirming that the site is back up.  I also can confirm that the case redirect is not working as I understood it to work.

**Comment by SteveALee** [comment]
@richnoah Excellent. 

What are the plans for GaaD? Are they still on track?

We need Michael to clue us in re redirects.

**Comment by SteveALee** [comment]
Double checking and https://www.w3.org/WAI/ARIA/apg/example-index/ is good!

**Comment by SteveALee** [comment]
@michael-n-cooper is it possible the reverse proxy for `/WAI` is breaking the case redirection logic on the w3c side? I can see nothing unusual about the way the site is served from the `gh-pages` branch of `wai-website repo`.

**Comment by richnoah** [comment]
as an update I was just able to get https://www.w3.org/wai/aria/apg/ to work and it resolved to https://www.w3.org/WAI/ARIA/apg/.  I tried this on both Chrome and Safari.  @SteveALee

**Comment by SteveALee** [comment]
Yay. So the fix was as per the original message in this issue. Closing :)
