### ISSUE TITLE
Incorrect banner markup in preview

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-aria-practices#96]
This is only critical for launch if it is a regression that will impact prod.

In prod at w3.org/wai/aria/apg, the banner has the latest template format containing a link and div:

~~~
  <div class="minimal-header-container">
    <div class="minimal-header-name">
      <a href="/WAI/aria/apg/">
          ARIA Authoring Practices Guide (APG)
      </a>
    </div>
      <div class="minimal-header-subtitle">
          How to build accessibility semantics into web patterns and widgets
      </div>
  </div>
~~~

In the [Netlify preview](https://wai-aria-practices2.netlify.app/aria/apg/)
the banner has the old markup:

~~~

  <div class="minimal-header-container">
    <div class="minimal-header-name">
          ARIA Authoring Practices Guide (APG)
    </div>
      <div class="minimal-header-subtitle">
          How to build accessibility semantics into web patterns and widgets
      </div>
  </div>
~~~

I hope this will not cause the old markup to be pushed to prod.

**Comment by richnoah** [comment]
@mcking65 the markup is updated during the build process to WAI.  This was the same issue that we saw prior to the first deploy as referenced in [Issue 68](https://github.com/w3c/wai-aria-practices/issues/68)

**Comment by mcking65** [comment]
Now, the preview site has the new markup. Closing.
